### ISSUE TITLE
issue when installation

### ISSUE THREAD

**Issue by tomstang** [yaozeliang/Library#3]
Hi master,

Greeting! i got an issue when i trying to run pip3 install -r requirements.txt,
errors on screen: ERROR: Could not find a version that satisfies the requirement numpy==1.3.0, 
and rest of items are same issue like Pandas, could you please help to fix?

thank you and BR,

**Comment by yaozeliang** [comment]
Sorry , this is  a strange issue,I can't run **pip freeze ->requirements.txt** to save  all the packages I used in the project. Can you try to install manually the package missing ?

I think it's due to the template I used.  beacuse I didn't create my own env when stating this project, just using their env folder

**Comment by yaozeliang** [comment]
Hi， I just updated requirements.txt file, everything will be ok now

**Comment by tomstang** [comment]
hello Liang,

happy new year!

thanks for fixing issue and version updating.
i imported the source code and run install again, same issue but for different pakages,  it seems the issue from source, following is what i did:
1. change the avaialbe version and re-install
2. manual download and install the some key pakages.
3. change back the version number, then re-install.
 issue fixed.

Thank you!

**Comment by yaozeliang** [comment]
Hi ,

Yes, I think it's beacause I used the the django template from third party while I didn't overwrite all modules. thanks for your review !
